### PR TITLE
some love for the database

### PR DESCRIPTION
**Pull request by beanieboi**
Goal:

fight database consistency early in the process. getting this right becomes harder and harder with more inconsistency in the database.

for reviewer: please run the migration against a production dump (if possible). adding the constraints fails if there are rows that violate the constraint.

database :rocket:

### CODE REVIEW

**Comment by wasi** [comment]
@beanieboi I think we should disable sqlite gem for development first. because each sqlite migration would change the schema (removing the fk).

**Comment by beanieboi** [comment]
@wasi agree, removing sqlite requires vagrant first, do i remember this correctly?

**Comment by beanieboi** [comment]
this needs #142 be merged first

**Comment by wasi** [comment]
yep right

**Comment by wasi** [comment]
@beanieboi the problem is, that in the live data we already have columns with nil values: https://travis-ci.org/asm-products/gamamia/builds/54766107

**Comment by wasi** [comment]
ok fixed. migrations passed, its live

**Pull request merged**
