### PR TITLE
Email Notification Preferences

### PR DESCRIPTION
**Pull request by christopherlai**
Users can opt-in/out of email notification

### CODE REVIEW

**Comment by JasonHoffmann** [comment]
Submitted a quick PR to change the styling a bit, but otherwise this looks great.

@wasi we'll have to make sure to set the "receive_newsletter" column in the DB to "t". Do you mind looking this over?

**Comment by wasi** [comment]
@JasonHoffmann you reverted the content cache column of the comments. It seems that the master branch should be merged (and rebased) into the mentions. @christopherlai could you check that this is in synch with master, migrations are not pending and test are passing?

adding / removing of columns could get messy. maybe a new branch with cherry-picked and squashed commits would clean things up...

**Comment by wasi** [comment]
@JasonHoffmann what was the issue with the schema.rb? (just to replicate and see if there are some pending issues)

**Comment by wasi** [comment]
@JasonHoffmann receive_newsletter will default to true: https://github.com/christopherlai/gamamia/blob/mentions/db/migrate/20150307045630_add_email_notifications_to_users.rb#L3

**Comment by wasi** [comment]
@JasonHoffmann @christopherlai ok this is a bit more tricky then I thought. I just tried to merge master quick, but there are some tricky conflicts. specially in the views and JS, where I'm not 100% sure. (mentions are 52 commits behind).

@JasonHoffmann we should merge that together tomorrow or on monday. To be sure that there are no issues in backend and frontend.

@christopherlai I'll come to you if there is anything you could do. But as far as I can see. your work is done for the bounty.

**Comment by christopherlai** [comment]
@wasi sure thing!

**Comment by JasonHoffmann** [comment]
@wasi, I'll take a look. The issue with schema was that the parent ID was removed from comments.

Let me try to merge this all together tomorrow.

**Comment by JasonHoffmann** [comment]
I can try merging everything into my fork, and make sure it all comes together. I think that'll be the cleanest way to do it.

**Comment by christopherlai** [comment]
@wasi i think in the future a better way of sending emails is through a background job queue. I am personally not a fan of sending emails in a model callback.

**Pull request merged**
