### PR TITLE
Added views for devise + enabled other methods of login/signup

### PR DESCRIPTION
**Pull request by christopherlai**

### CODE REVIEW

**Comment by christopherlai** [comment]
@JasonHoffmann I added a sign up and login link to the header. I generated the devise views, app/views/devise.

Is the plan to use account locks and confirmations?

**Comment by JasonHoffmann** [comment]
I can take a look at this tomorrow. Definitely confirmations. Don't know what you mean by account locks?

**Comment by christopherlai** [comment]
@JasonHoffmann devise has this feature where after a X amount of times a login fails the account is locked.

**Comment by JasonHoffmann** [comment]
@christopherlai Looking good, but a couple of things. First, @wasi mentioned that you should add a bit more test coverage for the email signup flow. I gave it a quick test, and ran into a couple of things. First of all, errors appear to be shown twice, not too sure why. You can replicate by trying to login with an email that already has a user assigned to it. Second, when signing up with your email, as opposed to oAuth, we don't need the second step of the flow, which asks you to "Add Email". Instead, can we add the "Signup for our newsletter" and "Occupation" to the main sign up form, and bypass this step altogether? Hope that makes sense.

**Comment by JasonHoffmann** [comment]
@christopherlai any update on this? I want to try to get this feature out this week.

**Comment by JasonHoffmann** [comment]
@beanieboi @wasi either one of you want to finish this up?

**Comment by wasi** [comment]
@JasonHoffmann I'm free this weekend, so I can have a look

**Pull request closed without merging**
